import matplotlib.pyplot as plt

class plt_Images():
    plt.show()
    # plt.title('predictions')
    # plt.ylabel('value')
    # plt.grid(True)
    # plt.autoscale(axis='x', tight=True)
    # plt.plot(flight_data['value'])
    # plt.plot(x,actual_predictions)
    # plt.show()

    # plt.title('predictions')
    # plt.ylabel('value')
    # plt.grid(True)
    # plt.autoscale(axis='x', tight=True)
    # plt.plot(flight_data['value'][-2000:])
    # plt.plot(x,actual_predictions)
    # plt.show()

    # plt.title('predictions')
    # plt.ylabel('value')
    # plt.grid(True)
    # plt.autoscale(axis='x', tight=True)
    # plt.plot(flight_data['value'][-500:])
    # plt.plot(x,actual_predictions)
    # plt.show()

    # plt.title('predictions')
    # plt.ylabel('value')
    # plt.grid(True)
    # plt.autoscale(axis='x', tight=True)
    # plt.plot(flight_data['value'][-200:])
    # plt.plot(x,actual_predictions)
    # plt.show()